## Project information
site_name: UP42 Python API
site_description: UP42 Python API
edit_uri: ''  #disables edit button

## Repository
repo_name: up42-py
repo_url: https://github.com/up42/up42-py
copyright: None

## Social Media
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/up42'
    - type: 'twitter'
      link: 'https://twitter.com/up42official'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/up42/'

## Page tree
nav:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Quickstart: 'quickstart/01_quickstart.md'
    - Tutorials:
      - Typical Usage: 'tutorials/02_typical_usage.md'
      - Catalog Search: 'tutorials/03_catalog.md'
    - Code Reference:
        - Api: 'reference/api.md'
        - Project: 'reference/project.md'
        - Workflow: 'reference/workflow.md'
        - Job: 'reference/job.md'
        - JobTask: 'reference/jobtask.md'
        - Tools: 'reference/tools.md'
    #- Swagger: 'swagger/swagger.md'


## Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: '_assets/logo.ico'
  favicon: '_assets/logo.ico'
  feature:
    tabs: false
  navigation_depth: 2

## Plugins
plugins:
  - search
  - autolinks
  - table-reader
  - mkdocstrings

## Custom theme additions
extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css

## Extensions
markdown_extensions:
  - markdown.extensions.admonition # For note/tip etc. blocks
  - markdown.extensions.codehilite:
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  #- pymdown.tabbed

google_analytics:
  - 'UA-XXXXXXXX-X' #add account
  - 'auto'